apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-server-exp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/av-rasmus/test-argocd-config.git
    targetRevision: HEAD
    path: charts/my-web-server
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: test-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
