apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/av-rasmus/test-argocd-config.git
    targetRevision: HEAD
    path: charts/rancher
    helm:
      values: |
        hostname: rancher.local
        ingress:
          hosts:
            - rancher.local
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true