hostname: rancher.local
ingress:
  enabled: true
  className: nginx
  tls:
    source: rancher
    hosts:
      - rancher.local
resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi
