hostname: localhost
ingress:
  enabled: true
  className: nginx
  hostname: rancher.localhost
  tls:
    source: rancher
resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 500m
    memory: 1Gi
