apiVersion: v2
name: my-web-server
type: application
version: 0.1.1
appVersion: "1.0"
dependencies:
  - name: nginx
    version: 19.0.3 # Replace with the desired Bitnami Nginx chart version
    repository: https://charts.bitnami.com/bitnami # Bitnami OCI repo